cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-central-1
    instance:
      data:
        enabled: false

server:
  forward-headers-strategy: framework

custom:
  invitation-codes: DUKE, HELLO_WORLD, STRATOSPHERIC # TODO: outsource them -> e.g. env variable or database
  sharing-queue: stratospheric-todo-sharing
  external-url: https://app.stratospheric.dev
  auto-confirm-collaborations: false
  confirm-email-from-address: noreply@stratospheric.dev
  environment: ${ENVIRONMENT_NAME}
